"""add kb_entries and query_logs tables

Revision ID: 2c58d4e01aba
Revises: 16cc432a9204
Create Date: 2026-05-28 21:28:48.883641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2c58d4e01aba'
down_revision: Union[str, Sequence[str], None] = '16cc432a9204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('example_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('question_patterns', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('prompt_template', sa.Text(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('applies_to', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requires_human', sa.Boolean(), nullable=False),
    sa.Column('use_fallback_ai', sa.Boolean(), nullable=False),
    sa.Column('last_prompt_used', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kb_applies_to', 'kb_entries', ['applies_to'], unique=False, postgresql_using='gin')
    op.create_index('idx_kb_example_active_priority', 'kb_entries', ['example_id', 'is_active', 'priority'], unique=False)
    op.create_index('idx_kb_example_category', 'kb_entries', ['example_id', 'category'], unique=False)
    op.create_index(op.f('ix_kb_entries_category'), 'kb_entries', ['category'], unique=False)
    op.create_index(op.f('ix_kb_entries_example_id'), 'kb_entries', ['example_id'], unique=False)
    op.create_index(op.f('ix_kb_entries_is_active'), 'kb_entries', ['is_active'], unique=False)
    op.create_table('query_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('example_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('kb_entry_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('response_source', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('kb_matched', sa.Boolean(), nullable=False),
    sa.Column('kb_priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kb_entry_id'], ['kb_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_query_logs_created', 'query_logs', ['created_at'], unique=False)
    op.create_index('idx_query_logs_example_user', 'query_logs', ['example_id', 'user_id'], unique=False)
    op.create_index('idx_query_logs_model', 'query_logs', ['model_used'], unique=False)
    op.create_index('idx_query_logs_source', 'query_logs', ['response_source'], unique=False)
    op.create_index(op.f('ix_query_logs_example_id'), 'query_logs', ['example_id'], unique=False)
    op.create_index(op.f('ix_query_logs_user_id'), 'query_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_logs_user_id'), table_name='query_logs')
    op.drop_index(op.f('ix_query_logs_example_id'), table_name='query_logs')
    op.drop_index('idx_query_logs_source', table_name='query_logs')
    op.drop_index('idx_query_logs_model', table_name='query_logs')
    op.drop_index('idx_query_logs_example_user', table_name='query_logs')
    op.drop_index('idx_query_logs_created', table_name='query_logs')
    op.drop_table('query_logs')
    op.drop_index(op.f('ix_kb_entries_is_active'), table_name='kb_entries')
    op.drop_index(op.f('ix_kb_entries_example_id'), table_name='kb_entries')
    op.drop_index(op.f('ix_kb_entries_category'), table_name='kb_entries')
    op.drop_index('idx_kb_example_category', table_name='kb_entries')
    op.drop_index('idx_kb_example_active_priority', table_name='kb_entries')
    op.drop_index('idx_kb_applies_to', table_name='kb_entries', postgresql_using='gin')
    op.drop_table('kb_entries')
    # ### end Alembic commands ###
