"""ProfileModuleItem

Revision ID: ac9377b4a9c4
Revises: 12e1bd557102
Create Date: 2026-05-24 14:55:30.315033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac9377b4a9c4'
down_revision: Union[str, Sequence[str], None] = '12e1bd557102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_module_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_module_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['profile_module_id'], ['profile_module.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_module_id', 'item_id', name='uq_pm_item')
    )
    op.create_index('idx_pm_item', 'profile_module_item', ['profile_module_id', 'item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pm_item', table_name='profile_module_item')
    op.drop_table('profile_module_item')
    # ### end Alembic commands ###
