"""add rag_chunks and rag_jobs tables

Revision ID: e1dd7008aab3
Revises: 2c58d4e01aba
Create Date: 2026-06-09 14:23:10.476626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from pgvector.sqlalchemy import Vector  # ✅ Import para pgvector
from sqlalchemy import ARRAY, String  # ✅ Import para ARRAY

# revision identifiers, used by Alembic.
revision: str = 'e1dd7008aab3'
down_revision: Union[str, Sequence[str], None] = '2c58d4e01aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ✅ Habilitar extensión pgvector (obligatorio para usar tipo VECTOR)
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_chunks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('section', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column('question', sa.Text(), nullable=True),
        sa.Column('answer', sa.Text(), nullable=True),
        sa.Column('keywords', ARRAY(String), nullable=True),  # ✅ ARRAY en lugar de Text
        sa.Column('embedding', Vector(384), nullable=True),  # ✅ Vector en lugar de pgvector.sqlalchemy.vector.VECTOR
        sa.Column('source_pdf', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('page_number', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rag_chunks_created', 'rag_chunks', ['created_at'], unique=False)
    op.create_index('idx_rag_chunks_keywords', 'rag_chunks', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index('idx_rag_chunks_section', 'rag_chunks', ['section'], unique=False)
    
    op.create_table('rag_jobs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('s3_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column('file_size', sa.Integer(), nullable=True),
        sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('chunks_created', sa.Integer(), nullable=True),
        sa.Column('processing_time_ms', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rag_jobs_created', 'rag_jobs', ['created_at'], unique=False)
    op.create_index('idx_rag_jobs_status', 'rag_jobs', ['status'], unique=False)
    op.create_index('idx_rag_jobs_user', 'rag_jobs', ['user_id'], unique=False)
    op.create_index(op.f('ix_rag_jobs_user_id'), 'rag_jobs', ['user_id'], unique=False)
    
    # ✅ Índice HNSW para búsqueda vectorial rápida (pgvector)
    op.execute('CREATE INDEX ON rag_chunks USING hnsw (embedding vector_cosine_ops)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_jobs_user_id'), table_name='rag_jobs')
    op.drop_index('idx_rag_jobs_user', table_name='rag_jobs')
    op.drop_index('idx_rag_jobs_status', table_name='rag_jobs')
    op.drop_index('idx_rag_jobs_created', table_name='rag_jobs')
    op.drop_table('rag_jobs')
    op.drop_index('idx_rag_chunks_section', table_name='rag_chunks')
    op.drop_index('idx_rag_chunks_keywords', table_name='rag_chunks', postgresql_using='gin')
    op.drop_index('idx_rag_chunks_created', table_name='rag_chunks')
    op.drop_table('rag_chunks')
    # Nota: No eliminamos la extensión 'vector' en downgrade para no romper otras tablas
    # ### end Alembic commands ###